Magazin/Controllers/AddProductController.cs
using Magazin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Numerics;

namespace Magazin.Controllers
{
    public class AddProductController : Controller
    {
        MagazinContext context;
        [BindProperty]
        Product product { get; set; }
        Category category { get; set; }
        Imeg imeg { get; set; }
        public AddProductController(MagazinContext db)
        {
            this.context = db;
        }
        public IActionResult AddCatedory(string catName)
        {
            context.Categories.Add(new Category() { Name = catName });
            context.SaveChanges();
            ViewBag.Categorya = context.Categories.AsNoTracking().ToList();
            return View("Index");
        }
        public async Task<IActionResult> AddProduct([Bind] Product product1)
        {
            var category = Request.Form["Category"];
            var catId = context?.Categories?.FirstOrDefault(o => o.Name.Equals(category)).Id;
            product1.CategoryId = catId;
            //var files = Request.Form.Files;

            await context.SaveChangesAsync();


            IFormFileCollection files = Request.Form.Files;

            var passrom = $@"{Directory.GetCurrentDirectory()}/wwwroot/Imeg2/{product1.Name.Replace(" ", "-")}";
            Directory.CreateDirectory(passrom);
            product1.PathLong = $"{files[0].FileName}";
            //using (var fs = new FileStream(product1.PathLong, FileMode.Create))
            //{
            //    await files[0].CopyToAsync(fs);
            //}
            //product1.PathLong = product1.PathLong.Split("wwwroot")[1];
            context.Products.Add(product1);
            await context.SaveChangesAsync();

            //product1 = context.Products.Where(o => o.Name == product1.Name).AsNoTracking().FirstOrDefault();
            // context.Imegs.Add(new Imeg() { Pass = files[0].FileName, ProductId = product1.Id });
            // context.AddAsync(product1);

            await context.SaveChangesAsync();

            //for (int i = 1; i < files.Count; i++)
            //{}
            var path = $@"{Directory.GetCurrentDirectory()}/wwwroot/Imeg2/{product1.Name.Replace(" ", "-")}";
            Directory.CreateDirectory(path);
            foreach (var file in files)
            {


                //imeg = new Imeg();
                //imeg.ProductId = context.Products.Where(o => o.Name == product1.Name).FirstOrDefault().Id;

                //imeg.Pass = $"{file.FileName}";
                string FullPath = $"{path}/{file.FileName}";
                using (var fs = new FileStream(FullPath, FileMode.Create))
                {
                    await file.CopyToAsync(fs);
                }
                var imeg = new Imeg();
                imeg.ProductId = product1.Id;
                imeg.Pass = file.FileName; /*imeg.Pass.Split("wwwroot")[1];*/
                await context.AddAsync(imeg);
            }


            await context.SaveChangesAsync();

            return Redirect("/Home/Index");
        }
        public IActionResult Index()
        {
            ViewBag.Categorya = context.Categories.AsNoTracking().ToList();

            return View();
        }
    }
}

Magazin/Controllers/BasketHistoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace Magazin.Controllers
{
    public class BasketHistoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Magazin/Controllers/BasketUserController.cs
using Magazin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Magazin.Controllers
{

    public class BasketUserController : Controller
    {

        MagazinContext context;
        [BindProperty]
        public User? user { get; set; }
        public Product products { get; set; }

        public BasketUserController(MagazinContext db)
        {
            this.context = db;

        }
        public IActionResult ToCart()
        {
            Dictionary<Product, string> pairs = new Dictionary<Product, string>();
            //List<Product> products = new List<Product>();        
            ViewBag.Products = context.Products.ToList();
            ViewBag.Photos = context.Imegs.ToList();
            ViewBag.Products = products;
            //ViewBag.User = user;             //Total Price
            double subPrice = 0;             //ViewBag.Count = products.Count(); 
            foreach (var item in pairs)
            {
                Product prod = item.Key;
                ViewData["Category"] = context.Categories.Find(prod.CategoryId).Name;
                subPrice += item.Key.Price;
            }
            ViewBag.SubPrice = subPrice;
           
            return View(pairs);
        }
        public async Task<IActionResult> Remove(int id)
        {
            string prodcart = HttpContext.Request.Cookies["cart"] ?? "";
            List<Product> cartProducts = JsonSerializer.Deserialize<List<Product>>(prodcart);

            // Отримання ідентифікатора продукту, який потрібно видалити з корзини
            int productIdToRemove = id;

            // Пошук продукту за його ідентифікатором та видалення з масиву
            Product productToRemove = cartProducts.FirstOrDefault(p => p.Id == productIdToRemove);
            if (productToRemove != null)
            {
                cartProducts.Remove(productToRemove);

                // Оновлення куки зі списком продуктів без видаленого продукту
                string updatedCart = JsonSerializer.Serialize(cartProducts);
                HttpContext.Response.Cookies.Append("cart", updatedCart);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
           
            string prodcart = HttpContext.Request.Cookies["cart"];
            if (!string.IsNullOrEmpty(prodcart))
            {
                var products = JsonSerializer.Deserialize<List<Product>>(prodcart);
                var productsInDb = new List<Product>();
                foreach (var product in products)
                {
                    int productId = product.Id;
                    int productAmount =1;

                    // Перевірка наявності продукту у базі даних
                    var productInDb = context.Products.FirstOrDefault(o => o.Id == productId);
                    if (productInDb != null)
                    {
                        productsInDb.Add(productInDb);

                        // Передача даних про продукт через ViewBag
                        ViewBag.ProductId = productInDb.Id;
                        ViewBag.ProdName = productInDb.Name;
                        ViewBag.ProdPrice = productInDb.Price;
                        ViewBag.ProdPathLong = productInDb.PathLong;
                        ViewBag.AmountProd = productAmount;
                        ViewBag.AmountProdMax = productInDb.Number;

                    }
                }

                // Передача списку продуктів в ViewBag
                ViewBag.Products = productsInDb;
            }
            return View();
        }
    }
}

Magazin/Controllers/RegistrationController.cs
using Magazin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace Magazin.Controllers
{
	public class RegistrationController : Controller
	{

        MagazinContext context;
        
       

        public RegistrationController(MagazinContext db)
        {
            this.context = db;

        }
        public IActionResult Index()
		{
			return View();
		}

		public IActionResult Login(string email, string password)
		{
            User user = context.Users.Where(o => o.Email == email && o.Password == password).AsNoTracking().FirstOrDefault();
            if (user != null)
            {
                

                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddDays(6);
                options.IsEssential = true;
                options.Path = "/";

                string str = JsonSerializer.Serialize(user);

                HttpContext.Response.Cookies.Append("UserLoggedIn", str, options);



                return Redirect("/Home/Index");

            }
            else
            {
                return Redirect("Index");
            }
        }

        public IActionResult Regist([Bind] User user)
        {


           
            user.RoleId = 2;
            context.Users.Add(user);

            context.SaveChanges();

            CookieOptions options = new CookieOptions();
            options.Expires = DateTime.Now.AddDays(6);
            options.IsEssential = true;
            options.Path = "/";

            string str = JsonSerializer.Serialize(user);

            HttpContext.Response.Cookies.Append("UserLoggedIn", str, options);

            return Redirect("/Home/Index");
        }

        public IActionResult Logout()
        {
            CookieOptions options = new CookieOptions();
            options.Expires = DateTime.Now;
            options.IsEssential = true;
            options.Path = "/";

            HttpContext.Response.Cookies.Append("UserLoggedIn", "", options);

            return Redirect("Index");
        }

    }
}

Magazin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magazin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Magazin.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar  navbar-expand navbar-dark " style="background-color:#949FE7">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" style="background-color:#386FE3" id="navbarTogglerDemo01">
                <img class="navbar-brand" width="100px" height="90px" src="/Imeg/GIV.gif">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link text-warning" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-warning" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link  text-warning" href="#">Disabled</a>
                    </li>
                </ul>
                <input form="buton1s" name="searh" class="form-control mr-sm-2 w-25" type="search" placeholder="Search" aria-label="Search">
                <form name="buton1s" class="form-inline bg-dark my-2 my-lg-0">
                    <button class="btn btn-outline-success my-2 my-sm-0 text-warning" type="submit">Search</button>
                </form>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
                    <li class="nav-item active">

                        <a class="nav-link text-warning" asp-controller="Registration" asp-action="Index"><img width="30px" height="30px" src="/Imeg/user1.png" /></a>

                    </li>
                    <li class="nav-item">


                        <a class="nav-link text-warning" asp-controller="BasketUser" asp-action="Index"><img width="30px" height="30px" src="/Imeg/basket1.png" /></a>

                    </li>
                    <li class="nav-item">


                        <a class="nav-link text-warning" asp-controller="BasketHistory" asp-action="Index"><img width="30px" height="30px" src="/Imeg/історія зам.png" /></a>

                    </li>
                    <li class="nav-item">


                        <a class="nav-link text-warning" asp-controller="AddProduct" asp-action="Index"><img width="30px" height="30px" src="/Imeg/addProduct2.png" /></a>

                    </li>
                    <li class="nav-item">


                        <a class="nav-link text-warning" asp-controller="Registration" asp-action="Logout"><img width="30px" height="30px" src="/Imeg/exit4.png" /></a>

                    </li>
                    <li class="nav-item">


                        <a class="nav-link text-warning" asp-controller="Home" asp-action="PowerBi"><img width="30px" height="30px" src="/Imeg/data-analytics.png" /></a>

                    </li>
                </ul>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Magazin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>